spring.application.name=microserviceeureka

#port
server.port=9999

#deactivate replication
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.max-threads-for-peer-replication=0
